### ISSUE TITLE
Need to be able to control value of UseNonZeroWinding

### ISSUE THREAD

**Issue by Zyl9393** [goki/freetype#4]
Over at https://github.com/golang/freetype/issues/90 some discussion has been happening regarding incorrectly rendered glyphs. It appears (?) that true type fonts should generally set `UseNonZeroWindOrder = true` on the rasterizer. However, the rasterizer [is inaccessible](https://github.com/goki/freetype/blob/master/truetype/face.go#L252) on instances of `truetype.Face` as well as in [`freetype.Context`](https://github.com/goki/freetype/blob/master/freetype.go#L61). Unless anyone knows more, we should make these accessible, i.e. change `r` to `R` in both structs. The value does not control any generated data and can be changed at any time between rasterization of glyphs.

**Comment by rcoreilly** [comment]
sounds good -- will do so soon..

**Comment by rcoreilly** [comment]
It was a lot simpler to just set UseNonZeroWindOrder = true on the rasterizer when it is first created.  I verified that this fixes the issue -- Apple Chancery euro symbol had it, for example.

**Comment by Zyl9393** [comment]
As I said, not sure if a font could require even-odd winding order. The change does work for me, though. Thanks.
